import numpy as np

MAX_ACCELERATION_M_S_2 = 10
MAX_BRAKING_M_S_2 = -4.1
MAX_WHEEL_ANGLE_RAD = 70 / 180 * np.pi

N = 5
dt = 0.1
MAX_CONTROL_WHEEL_ANGLE_RAD = 70 / 180 * np.pi
MAX_CONTROL_ACCELERATION_M_S_2 = 10
MAX_CONTROL_BRAKING_M_S_2 = -4.1
PATH_TOLERANCE_M = 0.5
V_REF = 10

FINE_X_COEF = 10
FINE_Y_COEF = 10
FINE_STEER_COEF = 10
FINE_ACC_COEF = 1
FINE_STEER_DOT_COEF = 100
FINE_ACC_DOT_COEF = 0
FINE_V_COEF = 20
FINE_THETA_COEF = 0
FINE_LATERAL_COEF = 40